### ISSUE TITLE
preferences: fix left-chat

### ISSUE THREAD

**Issue by xDashh** [MemeLabs/Rustla2#64]
Multiple reports of left-chat not working reliably. Need to figure out details.

**Comment by xDashh** [comment]
My reproducible tests don't work anymore and no more complaints lately. Some recent change or maybe just a rebuild might have fixed something, closing until new reports 🤔

**Comment by xDashh** [comment]
Happening again, probably reproducible. Seems related to user-specified pages only.

**Comment by KenanY** [comment]
I think the bug is [here](https://github.com/MemeLabs/Rustla2/blob/b8517596b19893445590294205e77e81cf0b8e4a/src/components/Stream.jsx#L121). If it's a `/:streamer` stream, then we set the document title and the stream, but we do not call `this.props.fetchProfileIfLoggedIn()` like we do in the `/:service/:channel` case, because of that early return on line 121. So, for the former kind of streams the profile is never fetched and hence left-chat is always the default: disabled.
